---
### ConfigMap for Database
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: bseg-devops
  name: jira-db-config-volume
  labels:
    app: jira8
data:
  dbconfig.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <jira-database-config>
      <name>defaultDS</name>
      <delegator-name>default</delegator-name>
      <database-type>postgres72</database-type>
      <schema-name>public</schema-name>
      <jdbc-datasource>
        <url>jdbc:postgresql://postgres-atlas.bseg-devops:5432/jira_prod</url>
        <driver-class>org.postgresql.Driver</driver-class>
        <username>jira_prod</username>
        <password>jira_prod</password>
        <pool-min-size>75</pool-min-size>
        <pool-max-size>150</pool-max-size>
        <pool-max-wait>30000</pool-max-wait>
        <validation-query>select 1</validation-query>
        <min-evictable-idle-time-millis>60000</min-evictable-idle-time-millis>
        <time-between-eviction-runs-millis>300000</time-between-eviction-runs-millis>
        <pool-max-idle>50</pool-max-idle>
        <pool-remove-abandoned>true</pool-remove-abandoned>
        <pool-remove-abandoned-timeout>300</pool-remove-abandoned-timeout>
        <pool-test-on-borrow>false</pool-test-on-borrow>
        <pool-test-while-idle>true</pool-test-while-idle>
      </jdbc-datasource>
    </jira-database-config>