apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresatlas
  namespace: bseg-devops
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi